name: "Homegear"
description: "Homegear as Homeassistant Addon"
version: "1.1.1"
slug: "homegear"
url: "https://github.com/home-assistant/addons-example/tree/main/example"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
map:
  - share:rw
  - config:rw
options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2017
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int
