name: "Homegear"
description: "Homegear as Homeassistant Addon"
version: "1.1.3"
slug: "homegear"
url: "https://github.com/home-assistant/addons-example/tree/main/example"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  2001/tcp: 2001
map:
  - share:rw
  - config:rw
